import { notFound } from "next/navigation";
import { requireGym } from "@/lib/auth";
import { formatInr, formatPaymentMethod } from "@/lib/domain";
import { PrintButton, ShareReceiptButton } from "@/components/print-button";
import { emailReceipt } from "@/app/actions/core";
import { Feedback } from "@/components/feedback";

export default async function ReceiptPage({ params, searchParams }: PageProps<"/receipts/[id]">) {
  const [{ id }, query] = await Promise.all([params, searchParams]);
  const { supabase, gym } = await requireGym();
  const { data: payment } = await supabase.from("payments").select("*, payment_reversals(amount_paise,reason,created_at), charges!inner(*, memberships!inner(*, members!inner(*)))").eq("id", id).eq("gym_id", gym.id).single();
  if (!payment) notFound();
  const charge = payment.charges;
  const membership = charge.memberships;
  const member = membership.members;
  const reversedPaise = payment.payment_reversals.reduce((sum: number, reversal: { amount_paise: number }) => sum + Number(reversal.amount_paise), 0);
  const success = typeof query.success === "string" ? query.success : undefined;
  const error = typeof query.error === "string" ? query.error : undefined;
  return <div className="receipt"><Feedback success={success} error={error}/><div className="receipt-head"><div><p className="eyebrow">Payment receipt</p><h1>{gym.name}</h1><div className="muted">{gym.address}<br/>{gym.phone} {gym.email}</div></div><div style={{ textAlign: "right" }}><strong>{payment.receipt_number}</strong><br/><span className="muted">{payment.paid_on}</span>{gym.gstin && <><br/><span>GSTIN {gym.gstin}</span></>}</div></div>{payment.voided_at && <div className="alert error"><strong>PAYMENT REVERSED</strong><br/>Reason: {payment.void_reason}. This receipt is retained for audit history and no longer counts toward collections.</div>}{!payment.voided_at && reversedPaise > 0 && <div className="alert"><strong>PARTIAL REVERSAL RECORDED</strong><br/>{formatInr(reversedPaise)} has been reversed. Net payment: {formatInr(Number(payment.amount_paise) - reversedPaise)}.</div>}<div className="form-grid"><div><span className="metric-label">Received from</span><h2 style={{ marginTop: 6 }}>{member.name}</h2><p className="muted">{member.member_code} · {member.phone}</p></div><div><span className="metric-label">For</span><h2 style={{ marginTop: 6 }}>{membership.plan_name} membership</h2><p className="muted">{membership.starts_on} — {membership.expires_on}</p></div></div><table className="table" style={{ margin: "28px 0" }}><tbody><tr><td>Plan price</td><td style={{ textAlign: "right" }}>{formatInr(Number(charge.subtotal_paise))}</td></tr><tr><td>Discount</td><td style={{ textAlign: "right" }}>− {formatInr(Number(charge.discount_paise))}</td></tr>{Number(charge.gst_rate_basis_points) > 0 && <tr><td>GST ({Number(charge.gst_rate_basis_points) / 100}%)</td><td style={{ textAlign: "right" }}>{formatInr(Number(charge.tax_paise))}</td></tr>}<tr><td><strong>Total amount</strong></td><td style={{ textAlign: "right" }}><strong>{formatInr(Number(charge.total_paise))}</strong></td></tr><tr><td><strong>Payment received via {formatPaymentMethod(payment.method)}</strong></td><td style={{ textAlign: "right" }}><strong>{formatInr(Number(payment.amount_paise))}</strong></td></tr>{reversedPaise > 0 && <><tr><td>Amount reversed</td><td style={{ textAlign: "right" }}>− {formatInr(reversedPaise)}</td></tr><tr><td><strong>Net payment</strong></td><td style={{ textAlign: "right" }}><strong>{formatInr(payment.voided_at ? 0 : Number(payment.amount_paise) - reversedPaise)}</strong></td></tr></>}</tbody></table>{payment.reference && <p><strong>Reference:</strong> {payment.reference}</p>}<div className="receipt-actions no-print"><PrintButton/><ShareReceiptButton receiptNumber={payment.receipt_number}/>{member.email && <form action={emailReceipt}><input type="hidden" name="payment_id" value={payment.id}/><button className="button secondary">Email to {member.email}</button></form>}</div></div>;
}
